version: '3.8'
services:
  db:
    image: mariadb
    container_name: dc_db
    ports:
      - 3306:3306
    volumes:
      - /home/asd1234op/dc/db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - dc
  cat:
    image: dc_cat
    container_name: dc_cat
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - /home/asd1234op/dc/image/cat:/cat
      - /home/asd1234op/dc/image/cat_find.png:/find.png
    networks:
      - dc

networks:
  dc:
    driver: bridge